# Generated by Django 3.1.1 on 2020-10-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
