# Generated by Django 3.1.1 on 2020-10-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201001_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
