# Generated by Django 3.1.1 on 2020-10-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20201009_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
