# Generated by Django 3.1.1 on 2020-10-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_auto_20201009_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='name'),
        ),
    ]
